### ISSUE TITLE
Milestone Update

### ISSUE THREAD

**Issue by lstar18** [lstar18/BusyBaby#10]
## User Story
The user will be able to edit the information they have inputted on any milestone 

## AC
WHEN the user clicks the edit icon
THEN the users initial inputs will appear 
AND the user can change the input to edit their previous "answers"

## Dev Notes
- [x] In EditMilestone.js, set the state of to an object that includes the keys from milestone data (title, description, imageUrl, date) and set them equal to empty strings
- [x] Run `componentDidMount` function, pass through `milestoneId` which you can get from `this.props.match.params`
- [x] Create `getSingleMilestone` function in milestoneData and then call it in component did mount 
- [x] Set milestone equal to response.data
- [x] Set state as object containing keys and then milestone.keyName
- [x] normal catch
- [x] Call change function that have an `e.preventDefault()` and setState of e.target.value for each key
- [x] in Render set title, description, imageUrl, date to this.state
- [x] in return create new div with `className="EditMilestone with col-12"`
- [x] import form and adapt form setting value to {title} and onChange= to {this.titleChange} * for example for all keys
- [x] Above render, create `updateMilestone` function  set `milestoneId` to `this.props.match.params` and then const all keys as an object that is set to this.state
- [x] create `updatedMilestone` object that defines each key
- [x] call `putMilestone` function from `milestoneData`
- [x] the then runs this.props.history.push function and the catch is normal err
- [ ] In the form, the button that says save milestone has an `onClick` attribute that calls `updateMilestone`
