### ISSUE TITLE
Stretch: Milestone List Toggle

### ISSUE THREAD

**Issue by lstar18** [lstar18/BusyBaby#13]
## User Story
When user clicks on milestone list, the user will be able to see all milestones entered in a list view

## Dev Notes
- [ ] In MilestoneList.js set state to an empty array called milestones

- [ ] Before render, create function that getMilestones from milestoneData getMilestonesbyUid

- [ ] the then passes through milestones and then sets state to ({ milestones })

- [ ] run componentDidMount function and call this.getMilestones function

- [ ] In render, Create a buildMilestoneList function that maps over an array of milestones

 - [ ] Define a component in the function called MilestoneList that sets a key of milestone.id and attribute of milestone to milestone

- [ ] Return a div with className of Milestone that contains an h1, another container div with d-flex flex-wrap and then call the function buildMilestoneList

- [ ] In MilestoneList.js in the render, bring in milestone through props and create prop type and shape

- [ ] In the return, return a list group from bootstrap

 - [ ] Display Title, date, and milestone type

**Comment by lstar18** [comment]
https://getbootstrap.com/docs/4.5/components/list-group/
