### ISSUE TITLE
Milestone Read

### ISSUE THREAD

**Issue by lstar18** [lstar18/BusyBaby#7]
## User Story
When the user clicks the milestones link in the navbar, they will see milestone cards that have been created
## AC
WHEN the milestone link is click
THEN the milestone cards will be displayed
AND the user can see all cards added

## Dev Notes
- [x] In SingleViewChild.js set state to an empty array called milestones
- [x] Before render, create function that `getMilestones` from `milestoneData` `getMilestonesbyChilId` 
- [x] the then passes through `milestones` and then sets state to `({ milestones })`
- [x] run componentDidMount function and call this.getMilestones function
- [x] In render, Create a `buildMilestoneCards` function that maps over an array of milestones 
- [x] Define a component in the function called `MilestoneCard` that sets a key of milestone.id and attribute of milestone to milestone
- [x] Return a div with `className` of Milestone that contains an `h1`, another container div with `d-flex flex-wrap` and then call the function `buildMilestoneCards`

- [x] In MilestoneCard.js in the render, bring in milestone through props and create prop type and shape
- [x] In the return, return a bootstrap card 
- [x] Create links for edit
- [x] Display Title, description, image, date, and milestone type

- [x] In milestoneData.js, create function that getsMilestoneByChildId passing in ChildId and creating a new Promise using orderBy="ChildId"&equalTo="${ChildId}"
- [x] then gets response and then sets theMilestones to response.data, milestones to empty array, if statement that uses Objectkeys passing through theMilestones and then run .forEach passing in theMilestoneId setting theMilestone[theMilestoneId].id equal to theMilestoneId then pushes to milestone array using (theMilestone[theMilestoneId])
- [x] resolve(milestones)
- [x] export getsMilestoneByChildId
