### ISSUE TITLE
Milestone Create

### ISSUE THREAD

**Issue by lstar18** [lstar18/BusyBaby#8]
## User Story
When user clicks on new milestone tab, they will be able to click a add button that generates a form in order for them to add a new milestone to their milestone tracker

## AC
WHEN the new milestone link is click
THEN the user sees a button to add a new milestone
AND a form is generated to add information for that new milestone 

## Dev Notes
- [x] In NewMilestone.js, set the state of to an object that includes the keys from milestone data (title, description, imageUrl, date) and set them equal to empty strings
- [x] Create change function that have an e.preventDefault() and setState of e.target.value for each key
- [x] in Render set title, description, imageUrl, date to this.state
- [x] in return create new div with `className="NewMilestone with col-12"`
- [x] import form and adapt form setting value to {title} and onChange= to {this.titleChange} * for example for all keys
- [x] Above render, create saveMilestone function that const all keys as an object that is set to this.state
- [x] create newMilestone object that defines each key
- [x] call postMilestone function from milestoneData
- [x] the then runs this.props.history.push function and the catch is normal err
- [x] In the form, the button that says save milestone has an onClick attribute that calls saveMilestone

**Comment by lstar18** [comment]
` domString += `<form id="add-envir-read-excursion-form" data-excursion-id="${excursionId}">`;
      domString += '<div class="form-group">';
      domString += '<label for="">Log Readings </label>';
      domString += '<select class="form-control" id="envir-reading-id">';
      readings.forEach((reading) => {
        domString += `<option value="${reading.id}">${reading.destinationId}, ${reading.TimeStamp}</option>`;
      });
      domString += '</select>';
      domString += '</div>';
      domString += '</form>';
`
use for dropdown for development type and child
