### ISSUE TITLE
Milestone Delete

### ISSUE THREAD

**Issue by lstar18** [lstar18/BusyBaby#9]
## User Story
There will be a delete button on each Milestone that is create in case the users wants to get rid of a milestone

## AC
WHEN the delete button gets clicked
THEN that milestone will disappear
AND the remainder of the milestones will still appear

## Dev Notes
- [x] In MilestoneCard.js add button to card that has an `onClick` with an anonymous function that calls `removeMilestone` passing through `milestone.id`
- [x] In SingleViewChild.js create function called `removeMilestone` that passes through `milestoneId` and then calls `removeMilestone` function from milestoneData.js and run `getMilestones()` in then
- [x] pass through `removeMilestone` into `MilestoneCard` component in `buildMilestoneCards` as an attribute
